### PR TITLE
Working towards compilation...

### PR DESCRIPTION
**Pull request by aphelionz**
Hello! :wave: 

I've spent the weekend trying to update this library so I can experiment with creating parts of `orbit-db` with it. I understand everything is still very WIP.

I got to one last error, trying to implement the now-defunct AsyncRead and AsyncWrite. If I can figure that out then I believe it should compile and I can work on getting the tests to pass.

So, I just wanted to show my progress and maybe get some feedback. Thank you for creating this library!

### CODE REVIEW

**Comment by dvc94ch** [comment]
Looking good!

**Comment by aphelionz** [comment]
Thanks. I'm updating the travis config now so that hopefully you can see the same errors as me...

**Comment by aphelionz** [comment]
Yep, there we go :+1: https://travis-ci.org/aphelionz/rust-ipfs/builds/585710817

**Comment by dvc94ch** [comment]
The issue seems to be that you have both tokio 0.1 and 0.2 in the dependency graph.

**Comment by aphelionz** [comment]
That was a last-ditch effort to get the traits I needed :stuck_out_tongue_closed_eyes:  since libp2p is expecting them. I think maybe I should try the extension types tokio 0.2 provides, `AsyncReadExt`, `AsyncWriteExt`

**Comment by dvc94ch** [comment]
libp2p is outdated. It would be great to move the mdns implementation into a separate crate and use the latest upstream libp2p. But as long as libp2p is still using tokio 0.1 it may be advisable to do the same here.

**Comment by dvc94ch** [comment]
FYI development has shifted. I'll probably archive this repo once those become more feature complete...
- https://github.com/dvc94ch/rust-ipld
- https://github.com/dvc94ch/rust-ipld-collections
- https://github.com/dvc94ch/ipld-daemon

**Comment by aphelionz** [comment]
Ok, I think what we need from the OrbitDB perspective is just pubsub and dag get+put. It looks like between your ipld libraries and libp2p itself we might have that covered...

**Comment by dvc94ch** [comment]
@aphelionz I'm really interested in getting some form of orbitdb working on top. Let me know if you have any issues. At the moment there are a lot of things missing and reliability/performance is not what it should be yet.

**Comment by aphelionz** [comment]
I'm gonna close this for now and focus on `rust-ipld`

**Pull request closed without merging**
